---
abstract: 'YubiKey authentication'
author:
  - 'Toby Corkindale, C<< <tjc at cpan.org> >>'
  - 'Toby Corkindale <tjc@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Authentication-Credential-YubiKey
no_index:
  directory:
    - inc
    - t
requires:
  Auth::Yubikey_WebClient: 2.00
  Catalyst::Exception: 0
  parent: 0
resources:
  homepage: http://github.com/TJC/Catalyst-Authentication-Credential-YubiKey
  license: http://dev.perl.org/licenses/
  repository: git://github.com/TJC/Catalyst-Authentication-Credential-YubiKey.git
version: 0.02
